version: "3"
services:
  prisma:
    image: prismagraphql/prisma:1.34
    env_file:
      - ./../.env
    restart: always
    ports:
      - "4466:4466"
    environment:
      PRISMA_CONFIG: |
        port: 4466
        managementApiSecret: ${PRISMA_MANAGEMENT_API_SECRET}
        databases:
          default:
            connector: mongo
            database: urban-matrix
            uri: mongodb://192.168.99.100:27017
  mongo:
    image: mongo:4.2
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo:/var/lib/mongo
volumes:
  mongo: ~
